### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by alicia8979** [GaussianGuaicai/GET3D-WebUI#1]
HI! I got an TypeError as follow:

Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
Traceback (most recent call last):
  File "GET3D_Demo.py", line 133, in <module>
    def retrive_a_img(imgs:list[np.ndarray]):
TypeError: 'type' object is not subscriptable

**Comment by GaussianGuaicai** [comment]
you need to first compile and install [nvdiffrast](https://github.com/NVlabs/nvdiffrast), GET3D relies on that library.
